#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x89EFD588E975D6DF (rbtcollins@hp.com)
#
Name     : traceback2
Version  : 1.4.0
Release  : 16
URL      : https://pypi.python.org/packages/source/t/traceback2/traceback2-1.4.0.tar.gz
Source0  : https://pypi.python.org/packages/source/t/traceback2/traceback2-1.4.0.tar.gz
Source99 : https://pypi.python.org/packages/source/t/traceback2/traceback2-1.4.0.tar.gz.asc
Summary  : Backports of the traceback module
Group    : Development/Tools
License  : Python-2.0
Requires: traceback2-python
Requires: linecache2
BuildRequires : contextlib2
BuildRequires : fixtures
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : testrepository
BuildRequires : testtools
BuildRequires : unittest2

%description
A backport of traceback to older supported Pythons.
>>> import traceback2 as traceback

%package python
Summary: python components for the traceback2 package.
Group: Default

%description python
python components for the traceback2 package.


%prep
%setup -q -n traceback2-1.4.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489435097
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1489435097
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
